config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :clients do
    member do
      get :accounts
      get :hackeo
    end
  end

  resources :bank_accounts, except: [:edit, :update, :destroy] do
    resources :transactions, shallow: true, only: [:new, :create, :index, :destroy]
    put :rates, on: :collection
  end

  resources :users, only: [:new, :create]
  get "/account" => "users#show"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates_presence_of :full_name
  validates_uniqueness_of :email, allow_blank: true
  has_many :bank_accounts
  has_many :transactions, through: :bank_accounts

  accepts_nested_attributes_for :bank_accounts

  def birth_decorado
    birth_at.strftime("%A, %B %d, %Y %l:%M %p")
  end

  def transactions_graph_series
    depositos = transactions.depositos.sum(:amount).round(2)
    retiros = transactions.retiros.sum(:amount).round(2)
    intereses = transactions.intereses.sum(:amount).round(2)
    diferencia = (depositos+intereses)-retiros

    {depositos: depositos, retiros: retiros, intereses: intereses, diferencia: diferencia}.to_json
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :get_client, only: [:show, :edit, :destroy, :update, :accounts, :hackeo]

  def index
    @clients = Client.order(:full_name)
    @table_class = true
  end

  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  def accounts
    @accounts = @client.bank_accounts
  end

  def hackeo
    @accounts = @client.bank_accounts
  end

  private
    def get_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:full_name, :birth_at, :email, :phone, bank_accounts_attributes: [:id, :balance])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def currency_availables
    ["Lempiras", "Dolares", "Euros"]
  end
end

app/views/clients/_acciones_individuales.html.erb
<li><%= link_to "Editar", edit_client_path(@client) %></li>
<li><%= link_to "Mis Cuentas", accounts_client_path(client) %></li>
<li><%= link_to "Hackeo!", hackeo_client_path(client) %></li>

app/views/clients/_client.html.erb
<tr class=<%= @table_class ? "odd" : "even" %> >
  <td><%= link_to client.id, client %></td>
  <td><%= client.full_name %></td>
  <td><%= client.birth_decorado %></td>
  <td>
    <% if client.email.present? %>
      <%= mail_to client.email, "Envia Correo" %>
    <% end %>
  </td>
  <td><%= client.bank_accounts.count %></td>
</tr>
<% @table_class = !@table_class %>

app/views/clients/_form.html.erb
<%= render partial: "shared/errors", locals: {obj: @client} %>
 <div class="form">
  <%= form_for @client do |f| %>
    <div class="form_row">
      <%= f.label :full_name, "Nombre Completo" %>
      <%= f.text_field :full_name, class: "form_input"  %>
    </div>
    <div class="form_row">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form_input" %>
    </div>
    <div class="form_row">
      <%= f.label :phone, "Telefono" %>
      <%= f.text_field :phone, class: "form_input" %>
    </div>
    <div class="form_row">
      <%= f.label :birth_at, "Nacimiento" %>
      <%= f.datetime_select :birth_at %>
    </div>
    <div class="form_row">
      <%= f.submit class: "form_submit" %>
      <%= link_to "Cancelar", clients_path, class: "button red" %>
    </div>
  <% end %>
</div>

app/views/clients/_submenu.html.erb
<div class="submenu">
  <ul>
    <li><%= link_to "Nuevo Cliente", new_client_path %></li>
  </ul>
</div>

app/views/clients/accounts.html.erb
<%= render "submenu" %>
<div class="center_content">
  <div id="right_wrap">
    <div id="right_content">
      <h2>Listas de Cuentas Bancarias de <%= @client.full_name %></h2>
      <table id="rounded-corner">
        <thead>
          <th>Id</th>
          <th>Cliente</th>
          <th>Balance</th>
          <th>Currency</th>
          <th>Tipo</th>
        </thead>
        <tbody>
          <%= render partial: "bank_accounts/bank_account", collection: @accounts, as: :account %>
        </tbody>
      </table>
      <h2>Grafica de Transacciones</h2>
      <div id="graph-container" data-graph-series=<%= @client.transactions_graph_series %>></div>
  </div>
  </div>
  <div class="sidebar" id="sidebar">
    <h2>Clientes</h2>
    <div class="sidebar_section_text">
      En esta area puedes ver las cuentas bancarias del cliente seleccionado.
    </div>
    <h2>Acciones</h2>
    <ul>
      <li><%= link_to "Regresar", @client %></li>
    </ul>
  </div>
</div>

app/views/clients/edit.html.erb
<%= render "submenu" %>
<div class="center_content">
  <div id="right_wrap">
    <div id="right_content">
      <h2>Editar Cliente</h2>
      <%= render "form" %>
    </div>
  </div>
  <div class="sidebar" id="sidebar">
    <h2>Clientes</h2>
    <div class="sidebar_section_text">
      En esta area puedes editar los datos del cliente seleccionado.
    </div>
    <h2>Acciones</h2>
    <ul>
      <li><%= link_to "Borrar", @client, method: :delete, data: { confirm: "Seguro?" } %></li>
      <%= render partial: "acciones_individuales", locals: {client: @client} %>
    </ul>
  </div>
</div>

app/views/clients/hackeo.html.erb
<%= render "submenu" %>
<div class="center_content">
  <div id="right_wrap">
    <div id="right_content">
      <h2>Hackeo de Cuentas de <%= @client.full_name %></h2>
       <div class="form">
        <%= form_for @client do |f| %>
          <%= f.fields_for :bank_accounts do |builder| %>
            <div class="form_row">
              <strong>#</strong>
              <%= builder.object.id %>
              <strong>Saldo:</strong>
              <%= builder.number_field :balance %>
            </div>
          <% end %>
          <div class="form_row">
            <%= f.submit "Hackear", class: "form_submit" %>
          </div>
        <% end %>
       </div>
    </div>
  </div>
  <div class="sidebar" id="sidebar">
    <h2>Clientes</h2>
    <div class="sidebar_section_text">
      En esta area puedes editar los saldos de las cuentas del cliente seleccionado.
    </div>
    <h2>Acciones</h2>
    <ul>
      <li><%= link_to "Regresar", @client %></li>
    </ul>
  </div>
</div>

app/views/clients/index.html.erb
<%= render "submenu" %>
<div class="center_content">
  <div id="right_wrap">
    <div id="right_content">
      <h2>Listado de Clientes</h2>
      <% if Client.any? %>
        <table id="rounded-corner">
          <thead>
            <tr>
              <th>Id</th>
              <th>Nombre</th>
              <th>Fecha de Nacimiento</th>
              <th>Email</th>
              <th>Contador de cuentas bancarias</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="5">Clientes Agregados al Sistema</td>
            </tr>
          </tfoot>
          <tbody>
            <%= render @clients %>
          </tbody>
        </table>
      <% else %>
        <em>No hay ningun cliente en la tabla</em>
      <% end %>
    </div>
  </div>
  <div class="sidebar" id="sidebar">
    <h2>Clientes</h2>
    <div class="sidebar_section_text">
      En esta area puedes ver los clientes creados ademas de poder agregar nuevos. Usa el Link de 'Enviar Correo' para enviarles directamente un email al cliente seleccionado.
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<%= render "submenu" %>
<div class="center_content">
  <div id="right_wrap">
    <div id="right_content">
      <h2>Nuevo Cliente</h2>
      <%= render "form" %>
    </div>
  </div>
  <div class="sidebar" id="sidebar">
    <h2>Clientes</h2>
    <div class="sidebar_section_text">
      En esta area puedes ver los clientes creados ademas de poder agregar nuevos. Usa el Link de 'Enviar Correo' para enviarles directamente un email al cliente seleccionado.
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<%= render "submenu" %>
<div class="center_content">
  <div id="right_wrap">
    <div id="right_content">
      <h2><%= @client.full_name %></h2>
      <p>
        <strong>Fecha de Nacimiento: </strong>
        <%= @client.birth_decorado %>
      </p>
      <p>
        <strong>Email: </strong>
        <%= @client.email %>
      </p>
      <p>
        <strong>Telefono: </strong>
        <%= @client.phone %>
      </p>
    </div>
  </div>
  <div class="sidebar" id="sidebar">
    <h2>Clientes</h2>
    <div class="sidebar_section_text">
      En esta area puedes ver los datos del cliente seleccionado.
    </div>
    <h2>Acciones</h2>
    <ul>
      <%= render partial: "acciones_individuales", locals: {client: @client} %>
    </ul>
  </div>
</div>