config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :clients do
    member do
      get :accounts
      get :hackeo
    end
  end

  resources :bank_accounts, except: [:edit, :update, :destroy] do
    resources :transactions, shallow: true, only: [:new, :create, :index, :destroy]
    put :rates, on: :collection
  end

  resources :users, only: [:new, :create]
  get "/account" => "users#show"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to :client
  has_one :debit_card
  has_many :transactions

  validates_presence_of :currency
  validates_numericality_of :balance, greater_than_or_equal_to: 0
  before_save :set_rate_segun_tipo

  default_scope { order(created_at: :desc) }
  scope :normales, -> { where(account_type: "Normal") }
  scope :vips, -> { where(account_type: "Vip") }
  scope :plazos, -> { where(account_type: "Plazo") }
  scope :cheques, -> { where(account_type: "Cheques") }

  scope :by_currency, -> (currency) {where(currency: currency)}

  accepts_nested_attributes_for :debit_card

  def depositar(monto)
    self.balance = self.balance + monto
  end

  def retirar(monto)
    self.balance = self.balance - monto
  end

  def self.generar_intereses
    collection = all
    collection.each do |account|
      amount = account.balance * 0.05
      account.balance = account.balance + amount
      #Generar una transaccion
      account.transactions.create(label: "Interes", amount: amount)
      account.save
    end
  end

  def rate_decorado
    "#{rate*100}%"
  end

  def balance_decorado
    "$ %.2f" % balance
  end

  def set_rate_segun_tipo
    case self.account_type
    when "Normal"
      self.rate = 0.02
    when "Vip"
      self.rate = 0.05
    when "Plazo"
      self.rate = 0.1
    else
      self.rate = 0;
    end
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController

  def index
    @accounts = BankAccount.includes(:client)

    if params[:query].present?
      q = params[:query]
      @accounts = @accounts.joins(:client)
        .where("bank_accounts.id LIKE '%#{q}%' OR
          clients.full_name LIKE '%#{q}%' OR
          bank_accounts.account_type LIKE '%#{q}%' OR
          bank_accounts.currency LIKE '%#{q}%'")
    end

    if request.xhr?
      render partial: "table", locals: {accounts: @accounts}, status: 200
    end
  end

  def show
    @account = BankAccount.find(params[:id])
  end

  def new
    @account = BankAccount.new
    @account.build_debit_card
  end

  def create
    @account = BankAccount.new(account_params)

    if @account.save
      redirect_to @account
    else
      render :new
    end
  end

  def rates
    BankAccount.generar_intereses
    @accounts = BankAccount.includes(:client)
    render partial: "table", locals: {accounts: @accounts}, status: 200
  end

  protected

    def account_params
      params.require(:bank_account).permit!
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
  def currency_availables
    ["Lempiras", "Dolares", "Euros"]
  end

  def types_availables
    ["Normal", "Vip", "Planilla", "Plazo", "Cheques"]
  end
end

app/views/bank_accounts/_bank_account.html.erb
<tr class="even">
  <td><%= link_to account.id, account %></td>
  <td><%= account.client.full_name %></td>
  <td><%= account.balance_decorado %></td>
  <td><%= account.currency %></td>
  <td><%= account.account_type %></td>
</tr>

app/views/bank_accounts/_table.html.erb
<table id="rounded-corner">
  <tr>
    <th>Id</th>
    <th>Cliente</th>
    <th>Balance</th>
    <th>Currency</th>
    <th>Tipo</th>
  </tr>
  <%= render partial: "bank_account", collection: accounts, as: :account %>
</table>

app/views/bank_accounts/index.html.erb
<div class="center_content">

  <h2>Cuentas Bancarias</h2>
  <% if @accounts.any? %>

    <div class="form">
      <%= form_tag bank_accounts_path, class: "js-filter-form", remote: true, method: :get do %>
        <div class="form_row">
          <%= text_field_tag :query, nil, placeholder: "Ingrese un texto para filtrar", class: "form_input" %>
          <%= submit_tag "Filtrar", class: "form_submit" %>
        </div>
      <% end %>
    </div>

    <div class="js-filtered-table">
      <%= render partial: "table", locals: {accounts: @accounts} %>
    </div>

  <% else %>
    <em>No hay ninguna cuenta creada</em>
  <% end %>
  <p>
  <%= link_to "Nueva Cuenta Bancaria", new_bank_account_path %>
  <%= link_to "Generar Intereses", rates_bank_accounts_path, method: :put, remote: true, class: "js_intereses" %>
  </p>

</div>

app/views/bank_accounts/new.html.erb
<div class="center_content">
  <div class="form">
    <h1>Nueva Cuenta Bancaria</h1>
    <%= render partial: "shared/errors", locals: {obj: @account} %>
    <%= form_for @account do |f| %>
      <div>
        <%= f.label :client_id, "Cliente ID" %>
        <%= f.select :client_id, Client.pluck(:full_name, :id) %>
      </div>
      <div>
        <%= f.label :balance %>
        <%= f.text_field :balance %>
      </div>
      <div>
        <%= f.label :currency %>
        <%= f.select :currency, currency_availables %>
      </div>
      <div>
        <%= f.label :account_type, "Tipo" %>
        <%= f.select :account_type, types_availables %>
      </div>

      <h2>TARJETA DE DEBITO</h2>
      <%= f.fields_for :debit_card do |builder| %>
        <div>
          <%= builder.label :number %>
          <%= builder.text_field :number %>
        </div>
        <h3>Fecha de Expiración (mes/año)</h3>
        <div>
          <%= builder.label :expiration_month %>
          <%= builder.number_field :expiration_month %>
          <%= builder.label :expiration_year %>
          <%= builder.number_field :expiration_year %>
        </div>
      <% end %>
      <div class="form_row">
        <%= f.submit class: "button green" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bank_accounts/show.html.erb
<div class="center_content">
  <h1>Cuenta Bancaria #<%= @account.id %></h2>
  <p>
    <strong>Cliente: </strong>
    <%= @account.client.full_name %>
  </p>
  <p>
    <strong>Balance: </strong>
    <%= @account.balance %>
  </p>
  <p>
    <strong>Currency: </strong>
    <%= @account.currency %>
  </p>
  <p>
    <strong>Tipo: </strong>
    <%= @account.account_type %>
  </p>
  <p>
    <strong>Tasa Interes: </strong>
    <%= @account.rate_decorado %>
  </p>
  <p>
    <strong>Tarjeta de debito asociada:</strong>
    <%= @account.debit_card.try(:decorate) %>
  </p>
  <%= link_to "Cuentas Bancarias", bank_accounts_path %>
  <%= link_to "Transacciones", bank_account_transactions_path(@account) %>
  <%= link_to "Depositar", new_bank_account_transaction_path(@account, label: "Deposito") %>
  <%= link_to "Retirar", new_bank_account_transaction_path(@account, label: "Retiro") %>
</div>