config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :clients do
    member do
      get :accounts
      get :hackeo
    end
  end

  resources :bank_accounts, except: [:edit, :update, :destroy] do
    resources :transactions, shallow: true, only: [:new, :create, :index, :destroy]
    put :rates, on: :collection
  end

  resources :users, only: [:new, :create]
  get "/account" => "users#show"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bank</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div id="panelwrap">
    <div class="header">
      <div class="title"><%= link_to "RoR Bank", root_path %></div>

      <div class="header_right">Welcome <%= current_user.name %>, <%= link_to "Mi Perfil", account_path, class: "settings" %>
      </div>

      <div class="menu">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Clientes", clients_path, "data-no-turbolink" => true %></li>
          <li><%= link_to "Cuentas Bancarias", bank_accounts_path %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        </ul>
      </div>
    </div>

    <%= yield %>
    <div class="clear"></div>
    <div class="footer">
      Panelo - Free Admin Template by <a href="htpp://csstemplatesmarket.com" target="_blank">CSSTemplatesMarket</a>
    </div>
</div>
  </div>
</body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bank</title>
  <%= stylesheet_link_tag    'public', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="header">
        <div class="header_content">

        <div class="logo"><a href="index.html"><%= Rails.application.config.site_name %></a></div>

        <div class="menu">
            <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Login", login_path %></li>
                <li><%= link_to "Registrarse", new_user_path %></li>
            </ul>
         </div>

        </div>
  </div>

  <div id="page_wrap">
    <div class="center_content">

      <%= yield %>
      <div class="clear"></div>
    </div>
  </div>
  <div id="footer">
  <div class="footer_content">
      <div class="footer_left">
        <h2>Latest Tweets</h2>
          <div class="tweets">
            <a href="#">Lincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</a>
            <a href="#">Lincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</a>
            <a href="#">Lincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</a>
            </div>
        </div>

      <div class="footer_left">
        <h2>Get in touch</h2>
          <div class="info">
            <p>
            Lincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam <br />
            Adress:  <span>info@email.com</span> <br />
      Phone:  <span>1234 345 978</span>
            </p>
                <div class="social">
                <a href="#"><%= image_tag "rss.gif" %></a>
                <a href="#"><%= image_tag "twitter.gif" %></a>
                </div>
            </div>
        </div>


        <div class="footer_right">
        <h2>Network Links</h2>
            <ul>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            </ul>

             <ul>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            <li><a href="#">Lincididunt ut labore et</a></li>
            </ul>
        </div>

     <div class="clear"></div>
  </div>
</div>
</body>
</html>